export const ChildPlanEnum = {
  ONE_CHILD: 'ONE_CHILD',
  TWINS: 'TWINS',
  MORE_THAN_TWO: 'MORE_THAN_TWO',
  NOT_SURE: 'NOT_SURE',
}

export const Ethnicity = {
  ASIAN: 'ASIAN',
  WHITE: 'WHITE',
  BLACK: 'BLACK',
  HISPANIC: 'HISPANIC',
  MIDDLE_EASTERN: 'MIDDLE_EASTERN',
  NATIVE_AMERICAN: 'NATIVE_AMERICAN',
  PACIFIC_ISLANDER: 'PACIFIC_ISLANDER',
  MIXED_RACE: 'MIXED_RACE',
  PREFER_NOT_TO_SAY: 'PREFER_NOT_TO_SAY',
  OTHER: 'OTHER',
}

// export const FertilityJourneyTiming = {
//   ASAP: 'ASAP',
//   NEXT_6_MONTHS: 'NEXT_6_MONTHS',
//   NEXT_YEAR: 'NEXT_YEAR',
//   NOT_SURE: 'NOT_SURE',
// }

export const JourneyStartTimingEnum = {
  ASAP: 'ASAP',
  NEXT_6_MONTHS: 'NEXT_6_MONTHS',
  NEXT_YEAR: 'NEXT_YEAR',
  NOT_SURE: 'NOT_SURE',
}


export const GenderIdentity = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  TRANSGENDER_MALE: 'TRANSGENDER_MALE',
  TRANSGENDER_FEMALE: 'TRANSGENDER_FEMALE',
  NON_BINARY: 'NON_BINARY',
  OTHER: 'OTHER',
}

export const PrimaryLanguage = {
  ENGLISH: 'ENGLISH',
  MANDARIN: 'MANDARIN',
  CANTONESE: 'CANTONESE',
  SPANISH: 'SPANISH',
  FRENCH: 'FRENCH',
  KOREAN: 'KOREAN',
  JAPANESE: 'JAPANESE',
  HINDI: 'HINDI',
  VIETNAMESE: 'VIETNAMESE',
  RUSSIAN: 'RUSSIAN',
  ARABIC: 'ARABIC',
  PORTUGUESE: 'PORTUGUESE',
  TAGALOG: 'TAGALOG',
  GERMAN: 'GERMAN',
  ITALIAN: 'ITALIAN',
  OTHER: 'OTHER',
}

export const ProgramInterest = {
  SURROGACY_EGG_DONOR: 'SURROGACY_EGG_DONOR',
  SURROGACY_ONLY: 'SURROGACY_ONLY',
  EGG_DONOR_ONLY: 'EGG_DONOR_ONLY',
  THIRD_PARTY_SURROGATE: 'THIRD_PARTY_SURROGATE',
  BRING_YOUR_OWN_SURROGATE: 'BRING_YOUR_OWN_SURROGATE',
  BRING_YOUR_OWN_SURROGATE_EGG: 'BRING_YOUR_OWN_SURROGATE_EGG',
  NOT_SURE: 'NOT_SURE',
}

export const Pronouns = {
  SHE_HER: 'SHE_HER',
  HE_HIM: 'HE_HIM',
  THEY_THEM: 'THEY_THEM',
  OTHER: 'OTHER',
}

export const SexualOrientation = {
  HETEROSEXUAL: 'HETEROSEXUAL',
  LGBTQIA: 'LGBTQIA',
  OTHER: 'OTHER'
}