export const ContactMethod = {
  FRIEND_REFERRAL: 'FRIEND_REFERRAL',
  SOCIAL_MEDIA: 'SOCIAL_MEDIA',
  GOOGLE_SEARCH: 'GOOGLE_SEARCH',
  OTHER: 'OTHER',
}

export const GovernmentAssistance = {
  FOOD_STAMPS: 'FOOD_STAMPS',
  MEDICAID: 'MEDICAID',
  CASH_ASSISTANCE: 'CASH_ASSISTANCE',
  FINANCIAL_AID: 'FINANCIAL_AID',
  WIC: 'WIC',
  SSI: 'SSI',
  PUBLIC_HOUSING: 'PUBLIC_HOUSING',
  SUBSIDIZED_CHILDCARE: 'SUBSIDIZED_CHILDCARE',
  STUDENT_LOANS: 'STUDENT_LOANS',
  OTHER_ASSISTANCE: 'OTHER_ASSISTANCE',
}

export const IncomeRange = {
  UNDER_30K: 'UNDER_30K',
  BETWEEN_30K_50K: 'BETWEEN_30K_50K',
  BETWEEN_50K_75K: 'BETWEEN_50K_75K',
  BETWEEN_75K_100K: 'BETWEEN_75K_100K',
  OVER_100K: 'OVER_100K',
  DECLINE_TO_STATE: 'DECLINE_TO_STATE',
}

export const MaritalStatus = {
  MARRIED: 'MARRIED',
  ENGAGED: 'ENGAGED',
  CO_HABITATING: 'CO_HABITATING',
  LIVING_SEPARATELY: 'LIVING_SEPARATELY',
  SINGLE: 'SINGLE',
  DIVORCED_FINALIZED: 'DIVORCED_FINALIZED',
  DIVORCED_IN_PROGRESS: 'DIVORCED_IN_PROGRESS',
  LEGALLY_SEPARATED: 'LEGALLY_SEPARATED',
  SEPARATED_INFORMALLY: 'SEPARATED_INFORMALLY',
}

export const PartnerSupportStatus = {
  YES: 'YES',
  NO: 'NO',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
}