export const navs = [
  {
    label: 'Parents',
    href: '/parents',
    children: [
      { label: 'Become Parents', href: '/become-parents' },
      { label: 'How to adopt', href: '/how-to-adopt' },
      { label: 'Adoption process', href: '/adoption-process' },
      { label: 'Adoption law', href: '/adoption-law' },
      { label: 'Adoption agency', href: '/adoption-agency' },
      { label: 'Adoption cost', href: '/adoption-cost' },
      { label: 'Adoption support', href: '/adoption-support' },
      { label: 'Adoption FAQ', href: '/adoption-faq' },
      { label: 'Adoption blog', href: '/adoption-blog' },
      { label: 'Adoption news', href: '/adoption-news' },
    ],
  },
  {
    label: 'Surrogates',
    href: '/surrogates',
    children: [
      { label: 'Become Surrogates', href: '/become-surrogates' },
      { label: 'How to be a surrogate', href: '/how-to-be-a-surrogate' },
      { label: 'Surrogacy process', href: '/surrogacy-process' },
      { label: 'Surrogacy law', href: '/surrogacy-law' },
      { label: 'Surrogacy agency', href: '/surrogacy-agency' },
      { label: 'Surrogacy cost', href: '/surrogacy-cost' },
      { label: 'Surrogacy support', href: '/surrogacy-support' },
      { label: 'Surrogacy FAQ', href: '/surrogacy-faq' },
      { label: 'Surrogacy blog', href: '/surrogacy-blog' },
    ],
  },
  {
    label: 'Resources',
    href: '/resources',
    children: [
      { label: 'Resources', href: '/resources' },
      { label: 'How to adopt', href: '/how-to-adopt' },
      { label: 'Adoption process', href: '/adoption-process' },
      { label: 'Adoption law', href: '/adoption-law' },
      { label: 'Adoption agency', href: '/adoption-agency' },
      { label: 'Adoption cost', href: '/adoption-cost' },
      { label: 'Adoption support', href: '/adoption-support' },
      { label: 'Adoption FAQ', href: '/adoption-faq' },
      { label: 'User guide', href: '/user' },
      { label: 'About us', href: '/about' },
    ],
  },
]
